In [114]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [115]:
###Load the trainded model,scaler pickle,onehot
model= load_model('model.h5')
with open('onehot_encoder.pkl', 'rb') as file:
    ohe_encoder = pickle.load(file)

##load the encoder and scaler pickle files
with open('label_encoder.pkl', 'rb') as file:
    label_encoder = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
#Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender':'Male',
    'Age': 40,
    'Tenure': 5,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1, 
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [ ]:
geography_encoded  = ohe_encoder.transform([[input_data['Geography']]]).toarray()
geography_df = pd.DataFrame(geography_encoded, columns=ohe_encoder.get_feature_names_out(['Geography']))
geography_df

c:\Users\kundr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [ ]:
input_df = pd.DataFrame([input_data])
input_df

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       5    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [ ]:
##Gender 
input_df['Gender'] = label_encoder.transform([input_data['Gender']])

In [ ]:
#combine the input data with the encoded geography
input_df = pd.concat([input_df, geography_df], axis=1)
#drop the original Geography column
input_df.drop('Geography', axis=1, inplace=True)
input_df


CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       5    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [ ]:
##scaling the input data
input_df_scaled = scaler.transform(input_df)
input_df_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.00134472, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [ ]:
##predict churn
prediction = model.predict(input_df_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step


array([[0.03615498]], dtype=float32)

In [ ]:
prediction_proba  = prediction

In [ ]:
prediction_proba

array([[0.03615498]], dtype=float32)

In [ ]:
if prediction_proba > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is likely to stay.")

The customer is likely to stay.
